- name: system-setup | bluetooth | install packages
  package:
    name:
      - alsa
      - alsa-utils
      - pulseaudio
      - pavucontrol
      - pamixer
      - pulseaudio-bluetooth

- name: system-setup | bluetooth | start service
  systemd:
    name: bluetooth
    enabled: yes
    state: started