- name: system-setup | bluetooth | install packages
  package:
    name:
      - bluez
      - bluez-utils
      - blueman
      - pulseaudio-bluetooth

- name: system-setup | bluetooth | start service
  systemd:
    name: bluetooth
    enabled: yes
    state: started