- name: Install X.org
  package:
    name: 
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xbindkeys
      - xclip
      - xsel
      - xterm
    state: latest

- name: Install LightDM
  package:
    name:
      - lightdm

- name: Enable LightDM
  systemd:
    name: lightdm
    enabled: yes

- name: Install WM
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm leftwm

- include_tasks: bluetooth.yml
  # todo: add when
  
- include_tasks: touchpad.yml
  # todo: add when