- name: desktop | minimal | install x.org
  package:
    name: 
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xrdb
      - xbindkeys
      - xclip
      - xsel
      - xterm
      - xsettingsd

- name: desktop | minimal | install compositor, background, and more
  package:
    name:
      - picom # compositor
      - nitrogen # background
      - unclutter # hide cursor after timeout
      - numlockx


# todo: picom-ibhagwan-git .... not picom-jonaburg-git

- name: desktop | minimal | check if compositor (picom-ibhagwan-git) is already installed
  stat:
    path: /usr/bin/picom
  register: picom_stat

# https://github.com/ibhagwan/picom
- name: desktop | minimal | install display-manager (picom-ibhagwan-git)
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm picom-ibhagwan-git
  when: not picom_stat.stat.exists

- name: desktop | minimal | check if display-manager (ly) is already installed
  stat:
    path: /usr/bin/ly
  register: ly_stat

- name: desktop | minimal | install display-manager (ly)
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm ly
  when: not ly_stat.stat.exists

- name: desktop | minimal | enable display-manager (ly)
  systemd:
    name: ly
    enabled: yes

- name: desktop | minimal | check if window-manager (leftwm) is already installed
  stat:
    path: /usr/bin/leftwm
  register: leftwm_stat

- name: desktop | minimal | install window-manager (leftwm)
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm leftwm
  when: not leftwm_stat.stat.exists
