- name: Install X.org
  package:
    name: 
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xbindkeys
      - xclip
      - xsel
      - xterm
    state: latest

- name: Configure x11 keymap
  command: localectl set-x11-keymap {{ config_system_keymap_short }}

#- name: Install LightDM
#  package:
#    name:
#      - lightdm
#      - lightdm-gtk-greeter

#- name: Enable LightDM
#  systemd:
#    name: lightdm
#    enabled: yes

- name: Check if Display-Manager already installed
  stat:
    path: /usr/bin/ly
  register: ly_stat

- name: Install Ly
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm ly
  when: not ly_stat.stat.exists

- name: Enable LightDM
  systemd:
    name: ly
    enabled: yes

- name: Check if WM already installed
  stat:
    path: /usr/bin/leftwm
  register: leftwm_stat

- name: Install WM
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm leftwm
  when: not leftwm_stat.stat.exists
