- name: desktop | minimal | install x.org
  package:
    name: 
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xrdb
      - xbindkeys
      - xclip
      - xsel
      - xterm
      - xsettingsd

- name: desktop | minimal | install compositor, background, and more
  package:
    name:
      - feh # background
      - unclutter # hide cursor after timeout
      - numlockx

- name: desktop | minimal | install compositor (picom)
  import_role:
    name: paru
  vars:
    package:
      - picom-git

- name: desktop | minimal | install display-manager (ly)
  import_role:
    name: paru
  vars:
    package:
      - ly

- name: desktop | minimal | enable display-manager (ly)
  systemd:
    name: ly
    enabled: yes

- name: desktop | minimal | check if leftwm is installed from source
  stat:
    path: /usr/local/bin/leftwm
  register: leftwm_stat

- name: desktop | minimal | install window-manager (leftwm)
  when: not leftwm_stat.stat.exists
  import_role:
    name: paru
  vars:
    package:
      - leftwm-git

#- name: desktop | minimal | install leftwm-theme-git
#  when: not leftwm_stat.stat.exists
#  import_role:
#    name: paru
#  vars:
#    package:
#      - leftwm-theme-git

- name: desktop | minimal | install polybar
  package:
    name:
      - polybar