- name: system-setup | network | install packages
  package:
    name:
      - networkmanager

- name: system-setup | network | enable and start NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes
    state: started