- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      community.general.pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

- hosts: all
  become: true
  roles:
    - base