- hosts: all
  connection: local
  become: true
  pre_tasks:
    - name: pre-run | update package cache
      tags: always
      pacman: update_cache=yes
      changed_when: False
      when: ansible_distribution == "Archlinux"

- hosts: all
  tags: base
  become: true
  roles:
    - base

#- hosts: personal
#  become: true
#  roles:
#    - personal