#!/bin/python3

# calculates the entropy of a TRUELY random generated password

import sys
import math

length=int(sys.argv[1])
base=int(sys.argv[2])

# entropy in bits
entropy=math.log2(pow(base, length))
entropy_bytes=int(entropy / 8)

# amount of attemptps statistically required to bruteforce
bruteforce=round(pow(2,entropy-1))

print(round(entropy, 2), "bits /", entropy_bytes, "bytes")
#print(f"{bruteforce:,}", "bruteforce")

if(entropy > 256):
    print("incredibly strong (overkill)")
elif(entropy > 128):
    print("very strong")
elif(entropy > 112):
    print("strong")
elif(entropy > 80):
    print("reasonable")
elif(entropy > 64):
    print("weak")
else:
    print("very weak")
