# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# aliases
alias ls='lsd'
alias ll='lsd -al'
alias ..='cd ..'
alias cpk='colorpicker --short --one-shot | xclip -selection clipboard'
alias alacritty='WINIT_X11_SCALE_FACTOR=1 alacritty'

alias k="kubectl"
alias cat="bat -p"

alias ga='git add .'
alias gs='git status'
alias gm='git commit -m'
alias gt='git tag'
alias gam="git add . && git commit -m"
alias gp='git push origin $(git branch --show-current)'

alias grep='grep --color'
alias vim='nvim'
alias vi='nvim'

alias please='sudo'
alias pls='sudo'

# address discord lag issues
# https://www.reddit.com/r/archlinux/comments/kcbjcu/comment/gfpalgx/?utm_source=share&utm_medium=web2x&context=3
alias discord='discord --no-sandbox'

# usage: 'mailenc <recipient-pubkey-file> <message-file>'
alias mailenc='gpg --encrypt --sign --armor --recipient-file'

# nvm
export NVM_SYMLINK_CURRENT=true
[ -d "/usr/share/nvm" ] && source /usr/share/nvm/init-nvm.sh

# exports
export EDITOR=vim
export VISUAL=vim
export HISTCONTROL=ignoreboth

# prompt
export PS1="\[\e[92m\]$(whoami | head -c 1)\[\e[m\]@\[\e[95m\]$(hostname | head -c 1)\[\e[m\]:\[\e[94m\]\w\[\e[m\] | \[\e[92m\]→\[\e[m\] "

# PATH
[[ -d $HOME/scripts ]] && export PATH="$HOME/scripts:$PATH"
[[ -d $HOME/go ]] && export PATH="$PATH:$HOME/go/bin"

# PGP / SSH
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

eval "$(starship init bash)"

macchina
