# Inserts a blank line between shell prompts
add_newline = true

[directory]
read_only = " "

[docker_context]
symbol = " "
format = '| [$symbol$context]($style) '

[git_branch]
symbol = " "
format = '| [$symbol$branch]($style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
symbol = " "
format = '| [$symbol($version)]($style) '

[java]
symbol = " "
style = "red bold"
format = '| [$symbol($version)]($style) '

[nodejs]
symbol = " "
format = '| [$symbol($version)]($style) '

[package]
symbol = " "
format = '| [$symbol$version]($style) '

[python]
format = '| [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '

[rust]
symbol = " "
format = '| [$symbol($version)]($style) '

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[scala]
symbol = " "
format = '| [$symbol($version)]($style) '
version_format = "v${major}.${minor}.${patch}"

[shell]
disabled = true

[localip]
disabled = false
ssh_only = true

[gcloud]
disabled = true

[status]
disabled = false
format = "[$status]($style) "

