- name: desktop | xfce | install xfce
  package:
    name: 
      - xorg-server
      - xorg-xinit
      - xfce4
      - xfce4-goodies
    state: latest

#- name: Install LightDM
#  package:
#    name:
#      - lightdm
#      - lightdm-gtk-greeter

#- name: Enable LightDM
#  systemd:
#    name: lightdm
#    enabled: yes

- name: desktop | minimal | check if display-manager (ly) is already installed
  stat:
    path: /usr/bin/ly
  register: ly_stat

- name: desktop | minimal | install display-manager (ly)
  become: yes
  become_user: aur_builder
  command: paru -S --cleanafter --skipreview --noprovides --nouseask --noconfirm ly
  when: not ly_stat.stat.exists

- name: desktop | minimal | enable display-manager (ly)
  systemd:
    name: ly
    enabled: yes