[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
themes = []

[[repos]]
url = "localhost"
name = "LOCAL"

[[repos.themes]]
name = "hertg"
directory = "/home/michael/.config/leftwm/themes/hertg"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "hertg_eww"
directory = "/home/michael/.config/leftwm/themes/hertg_eww"
version = "0.0.0"
leftwm_versions = "*"
current = true
