- name: software | kvm | install packages
  # ebtables? vde2? openbsp-netcat? iptables?
  package:
    name:
      - qemu
      - libvirt
      - dnsmasq
      - bridge-utils
      - ovmf # uefi support
      - virt-manager
      - virt-viewer

- name: software | kvm | set unix_sock_group to 'libvirt'
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    state: present
    regexp: 'unix_sock_group\s*=\s*'
    line: 'unix_sock_group = "libvirt"'

- name: software | kvm | set unix_sock_rw_perms to '0770'
  lineinfile:
    dest: /etc/libvirt/libvirtd.conf
    state: present
    regexp: 'unix_sock_rw_perms\s*=\s*'
    line: 'unix_sock_rw_perms = "0770"'

- name: software | kvm | create 'libvirt' group
  group:
    name: libvirt
    state: present

- name: software | kvm | add user '{{ config_username }}' to 'libvirt' group
  user:
    name: "{{ config_username }}"
    append: yes # add user to groups, don't remove from others
    groups: 
      - libvirt

- name: software | kvm | start and enable libvirt daemon
  systemd:
    name: libvirtd
    enabled: yes
    state: started

- name: software | kvm | check if default network is autostarted
  command: virsh net-info default
  register: virsh_net_status
  changed_when: false

- name: software | kvm | autostart 'default' network
  when: virsh_net_status.stdout | regex_search("Autostart:\s*no")
  command: virsh net-autostart default