- name: software | multimedia | install file viewers
  package:
    name:
      - sxiv # image viewer
      - llpp # document viewer
      - ffmpeg # video
      - maim # screenshot

- name: software | multimedia | install pdf editor
  import_role:
    name: paru
  vars:
    package:
      - masterpdfeditor-free


