# Resource: https://tldp.org/HOWTO/PPP-HOWTO/root.html

- name: software | netextender | install netextender
  import_role:
    name: paru
  vars:
    package:
      - netextender

- name: software | netextender | create user group 'ppp'
  group:
    name: ppp
    state: present

- name: software | netextender | add user '{{ config_username }}' to 'ppp' group
  user:
    name: "{{ config_username }}"
    append: yes # add user to groups, don't remove from others
    groups: 
      - ppp

- name: software | netextender | change ownership of '/usr/sbin/pppd'
  file:
    path: /usr/sbin/pppd
    group: ppp
    mode: 04750 # -rwsr-x---

# https://wiki.archlinux.org/title/Ppp#pppd_cannot_load_kernel_module_ppp_generic
- name: software | netextender | load ppp_generic kernel module
  register: ppp_generic
  copy:
    dest: /etc/modprobe.d/ppp.conf
    content: |
      alias char-major-108 ppp_generic

- name: software | netextender | notice
  when: ppp_generic.changed
  debug:
    msg: 'a restart may be required to connect via netextender'

