- name: software | obs | install OBS and v4l2loopback
  package:
    name:
      - obs-studio
      - v4l2loopback-dkms

- name: software | obs | install obs-v4l2sink
  import_role:
    name: paru
  vars:
    package:
      - obs-v4l2sink

# todo: configure?
