- name: software | utils | basic system utilities
  package:
    name:
      - git
      - openssh
      - man
      - htop
      - neovim
      - inetutils # provides commands like "hostname"
      - bind # provides commands like nslookup
      - zip
      - unzip
      - lzip
      - dkms # dynamic kernel modules

- name: software | utils | install git, lsd, openssh, man, neovim, etc
  package:
    name:
      - lsd # 'ls' alternative
      - alacritty # terminal
      - dmenu # launcher
      - rofi # launcher
      - ranger # console file manager
      - ueberzug # console image preview
    state: latest

- name: software | utils | install plugin manager for neovim
  shell: 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

- name: software | utils | install plugins for neovim
  shell: 'nvim +PlugInstall +qa --headless'
  