- name: ansible-setup | update ansible to latest version
  package:
    name: 
      - ansible
      - rsync # required for synchronize task
    state: latest

#- name: ansible setup | install galaxy requirements
#  command: ansible-galaxy collection install -r requirements.yml