- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - import_tasks: ansible_setup.yml

  - import_tasks: system_setup/locale.yml

  - import_tasks: system_setup/user.yml

  - import_tasks: system_setup/aur.yml
    when: ansible_distribution == 'Archlinux'

  - import_tasks: system_setup/touchpad.yml

  - import_tasks: system_setup/graphics.yml

  # MINIMAL
  - import_tasks: desktop/minimal/install.yml
    when: desktop == 'minimal'
  
  - import_tasks: desktop/minimal/bluetooth.yml
    when: desktop == 'minimal'
    
  - import_tasks: desktop/minimal/network.yml
    when: desktop == 'minimal'
  
  # XFCE
  - import_tasks: desktop/xfce/install.yml
    when: desktop == 'xfce'
  
  - import_tasks: software/utils.yml