- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - import_tasks: ansible_setup.yml

  # paru must be installed first, so it can be used in the upcoming tasks
  - import_tasks: system_setup/aur.yml
    when: ansible_distribution == 'Archlinux'

  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/security.yml
  - import_tasks: system_setup/user.yml  
  - import_tasks: system_setup/touchpad.yml
  - import_tasks: system_setup/graphics.yml
  - import_tasks: system_setup/fonts.yml
  - import_tasks: system_setup/icons.yml
  - import_tasks: system_setup/audio.yml
  - import_tasks: system_setup/power.yml

  - import_tasks: system_setup/bluetooth.yml
    when: bluetooth is defined and bluetooth == true

  - when: desktop is defined
    block:

      # MINIMAL
      - import_tasks: desktop/minimal/install.yml
        when: desktop == 'minimal'

      - import_tasks: desktop/minimal/bluetooth.yml
        when: desktop == 'minimal'
        
      - import_tasks: desktop/minimal/network.yml
        when: desktop == 'minimal'
      
      - import_tasks: desktop/minimal/notification.yml
        when: desktop == 'minimal'
      
      # XFCE
      - import_tasks: desktop/xfce/install.yml
        when: desktop == 'xfce'
      
      # Gnome
      - import_tasks: desktop/gnome/install.yml
        when: desktop == 'gnome'

      # Desktop Post-Install
      - import_tasks: desktop/post_desktop_install.yml
      
  - import_tasks: software/utils.yml
  - import_tasks: software/multimedia.yml
  - import_tasks: software/browser.yml

  # post install
  - import_tasks: post_install.yml
