- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:

  - import_tasks: ansible_setup.yml

  # paru must be installed first, so it can be used in the upcoming tasks
  - import_tasks: system_setup/aur.yml
    when: ansible_distribution == 'Archlinux'

  - import_tasks: system_setup/locale.yml
  - import_tasks: system_setup/security.yml
  - import_tasks: system_setup/user.yml  
  - import_tasks: system_setup/touchpad.yml
  - import_tasks: system_setup/graphics.yml
  - import_tasks: system_setup/fonts.yml
  - import_tasks: system_setup/icons.yml
  - import_tasks: system_setup/audio.yml
  - import_tasks: system_setup/power.yml
  - import_tasks: system_setup/utils.yml
  - import_tasks: system_setup/thunderbolt.yml
  - import_tasks: system_setup/firmware.yml
  - import_tasks: system_setup/multimedia.yml

  - import_tasks: system_setup/bluetooth.yml
    when: bluetooth is defined and bluetooth == true

  - when: desktop is defined
    block:

      # MINIMAL
      - import_tasks: desktop/minimal/install.yml
        when: desktop == 'minimal'
        
      - import_tasks: desktop/minimal/network.yml
        when: desktop == 'minimal'
      
      - import_tasks: desktop/minimal/notification.yml
        when: desktop == 'minimal'
      
      # XFCE
      - import_tasks: desktop/xfce/install.yml
        when: desktop == 'xfce'
      
      # Gnome
      - import_tasks: desktop/gnome/install.yml
        when: desktop == 'gnome'

      # Desktop Post-Install
      - import_tasks: desktop/post_desktop_install.yml
  
  
  # optional software
  - import_tasks: software/firefox.yml

  - import_tasks: software/brave.yml
    when: brave is defined and brave == true

  - import_tasks: software/masterpdf_editor.yml
    when: masterpdfeditor is defined and masterpdfeditor == true

  - import_tasks: software/kvm.yml
    when: kvm is defined and kvm == true

  - import_tasks: software/discord.yml
    when: discord is defined and discord == true

  - import_tasks: software/vscode.yml
    when: vscode is defined and vscode == true
  
  - import_tasks: software/obs.yml
    when: obs is defined and obs == true

  - import_tasks: software/intellij.yml
    when: intellij is defined and intellij == true
  
  - import_tasks: software/nodejs.yml
    when: nodejs is defined and nodejs == true
  
  - import_tasks: software/odbc.yml
    when: odbc is defined and odbc == true
  
  - import_tasks: software/wompiler.yml
    when: wompiler is defined and wompiler == true

  - import_tasks: software/sbt.yml
    when: sbt is defined and sbt == true

  - import_tasks: software/android.yml
    when: android is defined and android == true
  
  - import_tasks: software/netextender.yml
    when: netextender is defined and netextender == true

  - import_tasks: software/remmina.yml
    when: remmina is defined and remmina == true

  - import_tasks: software/jdk.yml
    when: jdk is defined and jdk == true

  - import_tasks: software/docker.yml
    when: docker is defined and docker == true
  
  - import_tasks: software/dbeaver.yml
    when: dbeaver is defined and dbeaver == true
  
  - import_tasks: software/spotify.yml
    when: spotify is defined and spotify == true
  
  - import_tasks: software/egpu_switcher.yml
    when: egpu_switcher is defined and egpu_switcher == true
  
  - import_tasks: software/teamviewer.yml
    when: teamviewer is defined and teamviewer == true

  - import_tasks: software/steam.yml
    when: steam is defined and steam == true

  # post install
  - import_tasks: post_install.yml
