- name: system-setup | audio | install packages
  package:
    name:
      - alsa-card-profiles
      - alsa-utils
      - pulseaudio
      - pavucontrol
      - pamixer

- name: system-setup | audio | install steelseries-arctis-pro-wireless
  import_role:
    name: install-from-git
  vars:
    dir_name: steelseries-arctis-pro-wireless
    git_url: https://github.com/hertg/steelseries-arctis-pro-wireless
    binary_check: steelseries-arctis-pro-wireless
