- name: system-setup | install base-devel, git, ssh
  package:
    name: 
      - base-devel
      - git
      - openssh
    state: latest

- name: system-setup | checkout paru (AUR helper)
  ansible.builtin.git:
    repo: 'git@github.com:Morganamilo/paru.git'
    dest: /tmp/paru

- name: system-setup | install paru (AUR helper)
  command: makepkg --syncdeps --install
  args:
    chdir: /tmp/paru
