- name: system-setup | install base-devel
  package:
    name: base-devel

- name: Install git
  package:
    name: git

- name: system-setup | checkout paru (AUR helper)
  ansible.builtin.git:
    repo: 'git@github.com:Morganamilo/paru.git'
    dest: /tmp/paru

- name: system-setup | install paru (AUR helper)
  command: makepkg --syncdeps --install
  args:
    creates: paru
    chdir: /tmp/paru
