# https://github.com/kewlfft/ansible-aur

- name: system-setup | aur | install base-devel, git
  package:
    name: 
      - base-devel
      - git
    state: latest

- name: system-setup | aur | check if paru is already installed
  stat:
    path: /usr/bin/paru
  register: paru_stat

- name: system-setup | aur | install paru
  when: not paru_stat.stat.exists
  block:

    - name: system-setup | aur | create aur_builder user
      user:
        name: aur_builder
        create_home: yes
        system: yes

    - name: system-setup | aur | allow aur_builder to run pacman
      lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    #- name: system-setup | aur | configure rustup for aur_builder
    #  command: rustup default stable
    #  become_user: aur_builder
    # -> this may only be necessary if rustup was installed beforehand..?

    - name: system-setup | aur | install paru
      import_role:
        name: install-from-git
      vars:
        dir_name: paru
        git_url: https://aur.archlinux.org/paru.git
