- name: system-setup | install base-devel, git, ssh
  package:
    name: 
      - base-devel
      - git
    state: latest

- name: system-setup | checkout paru (AUR helper)
  ansible.builtin.git:
    repo: 'https://github.com/Morganamilo/paru.git'
    dest: /tmp/paru

- name: system-setup | aur | change ownership of paru repository
  path: /tmp/paru
  state: directory
  owner: "{{ config_username }}"
  group: "{{ config_username }}"
  recurse: yes

- name: system-setup | install paru (AUR helper)
  become_user: "{{ config_username }}"
  command: makepkg --syncdeps --install
  args:
    chdir: /tmp/paru
