- name: system-setup | bluetooth | install software
  package:
    name: 
      - bluez
      - bluez-utils
      - blueman
      - pulseaudio-bluetooth

- name: system-setup | bluetooth | start service
  systemd:
    name: bluetooth
    enabled: yes
    state: started