- name: system-setup | graphics | install nvidia proprietary drivers
  package:
    name:
      - nvidia
      - nvidia-lts # required ???
      - nvidia-utils
      - nvidia-settings
  when:
    - ansible_distribution == "Archlinux"
    - gpu is defined
    - gpu == "nvidia"