- name: system-setup | graphics | install nvidia proprietary drivers
  package:
    name:
      - nvidia
      - nvidia-lts # required ???
      - nvidia-utils
      - nvidia-settings
  when:
    - ansible_distribution == "Archlinux"
    - gpu is defined
    - gpu == "nvidia"

- name: system-setup | graphics | install amd drivers
  package:
    name:
      - mesa
      - lib32-mesa # necessary for steam
      - vulkan-radeon
      - xf86-video-amdgpu
  when:
    - ansible_distribution == "Archlinux"
    - gpu is defined
    - gpu == "amd"