# https://wiki.archlinux.org/title/locale
# https://serverfault.com/a/981742

- name: system-setup | locale | add locale
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: system-setup | locale | add language
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: system-setup | locale | configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  template:
    src: templates/locale.conf.j2
    dest: /etc/locale.conf

- name: system-setup | locale | configure keymap to '{{ config_system_keymap }}'
  template:
    src: templates/vconsole.conf.j2
    dest: /etc/vconsole.conf


