# https://wiki.archlinux.org/title/locale
# https://serverfault.com/a/981742

- name: system-setup | add locale
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: system-setup | add language
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: Configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  command: localectl set-locale LANG={{ config_system_locale }} LC_MESSAGES={{ config_system_language }}
