# https://wiki.archlinux.org/title/locale
# https://serverfault.com/a/981742

- name: system-setup | locale | add locale
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: system-setup | locale | add language
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: system-setup | locale | configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  # todo: change to lineinfile?
  command: >
    localectl set-locale 
    LANG={{ config_system_language }} 
    LC_TIME={{ config_system_locale }} 
    LC_MEASUREMENT={{ config_system_locale }}
    LC_MONETARY={{ config_system_locale }}
    LC_NUMERIC={{ config_system_locale }}
    LC_TELEPHONE={{ config_system_locale }}

- name: system-setup | locale | configure keymap to '{{ config_system_keymap }}'
  # todo: change to lineinfile
  command: localectl set-keymap {{ config_system_keymap }}

