# https://wiki.archlinux.org/title/locale
# https://serverfault.com/a/981742

- name: system-setup | locale | add locale
  locale_gen:
    name: "{{ config_system_locale }}"
    state: present

- name: system-setup | locale | add language
  locale_gen:
    name: "{{ config_system_language }}"
    state: present

- name: system-setup | locale | configure locale to '{{ config_system_locale }}' and language to '{{ config_system_language }}'
  command: localectl set-locale LANG={{ config_system_locale }} LC_MESSAGES={{ config_system_language }}

- name: system-setup | locale | configure keymap to '{{ config_system_keymap }}'
  command: localectl set-keymap {{ config_system_keymap }}

- name: system-setup | locale | configure x11 keymap
  command: localectl set-x11-keymap {{ config_system_keymap_short }}

#- name: system-setup | locale | configure vconsole
#  lineinfile:
#    path: /etc/vconsole.conf
#    line: 'KEYMAP={{ config_system_keymap }}'
#    create: yes
