- name: system-setup | add en_US
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: system-setup | add de_CH
  locale_gen:
    name: de_CH.UTF-8
    state: present

- name: system-setup | set LANG to en_US
  command: localectl set-locale LANG=en_US.UTF-8
  when: locale.changed