- name: system-setup | security | basic system utilities
  package:
    name:
      - libsecret
      - seahorse # passwords and keys
      - ufw
      - gpa # graphical GPG key manager
      - libfido2

#- name: system-setup | security | check if ufw is enabled
#  command: ufw status
#  register: ufw_status
#  changed_when: false
#
#- name: system-setup | security | enable ufw
#  when: "'inactive' in ufw_status.stdout"
#  command: ufw enable

- name: system-setup | security | set coredump mode for setuid (CVE-2022-4415)
  ansible.posix.sysctl:
    name: fs.suid_dumpable
    value: 0
    state: present

- name: system-setup | security | disable unprivileged user namespaces
  ansible.posix.sysctl:
    name: kernel.unprivileged_userns_clone
    value: 0
    state: present
