- name: software | utils | basic system utilities
  package:
    name:
      - libsecret
      - seahorse # passwords and keys
      - ufw
      - gpa # graphical GPG key manager

- name: software | security | check if ufw is enabled
  command: ufw status
  register: ufw_status
  changed_when: false

- name: software | security | enable ufw
  when: "'inactive' in ufw_status.stdout"
  command: ufw enable