#- name: user | root
#  user:
#    name: root
#    password_lock: yes

- name: system-setup | user | install sudo
  package:
    name: sudo
    state: latest

- name: system-setup | user | create 'wheel' group
  group:
    name: wheel
    state: present

- name: system-setup | user | allow 'wheel' group to run sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: system-setup | user | create user group '{{ config_username }}'
  group:
    name: "{{ config_username }}"
    state: present

- name: system-setup | user | create user '{{ config_username }}'
  user:
    name: "{{ config_username }}"
    append: yes # add user to groups, don't remove from others
    groups: 
      - "{{ config_username }}"
      - wheel
    state: present
    create_home: yes

- name: system-setup | user | create config directory for user '{{ config_username }}'
  file:
    path: /home/{{ config_username }}/{{ item.dir }}
    state: directory
    owner: "{{ config_username }}"
    group: "{{ config_username }}"
    mode: 0700
  with_items:
    - { dir: '.config' }

- name: system-setup | user | copy user configs
  copy:
    src: userconfig/{{ item.src }}
    dest: /home/{{ config_username }}/{{ item.dest }}
    owner: "{{ config_username }}"
    group: "{{ config_username }}"
    mode: preserve
  with_items:
    - { src: 'bash_profile', dest: '.bash_profile' }
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'xprofile', dest: '.xprofile' }
    - { src: 'Xresources', dest: '.Xresources' }
    - { src: 'xsettingsd', dest: '.xsettingsd' }
    - { src: 'xbindkeysrc', dest: '.xbindkeysrc' }
    - { src: 'inputrc', dest: '.inputrc' }
    - { src: 'gitconfig', dest: '.gitconfig' }
    - { src: 'nvim', dest: '.config/'}
    - { src: 'picom', dest: '.config/'}
    - { src: 'ranger', dest: '.config/'}
    - { src: 'sxiv', dest: '.config/'}
    - { src: 'llpp.conf', dest: '.config/'}
    - { src: 'fontconfig', dest: '.config/'}
    - { src: 'gtk-3.0', dest: '.config/'}
    - { src: 'leftwm', dest: '.config/'}
    - { src: 'macchina', dest: '.config/'}
    - { src: 'alacritty', dest: '.config/'}
    - { src: 'rofi', dest: '.config/'}
    - { src: 'bottom', dest: '.config/'}
