#- name: user | root
#  user:
#    name: root
#    password_lock: yes

- name: system-setup | user | install sudo
  package:
    name: sudo
    state: latest

- name: system-setup | user | create 'wheel' group
  group:
    name: wheel
    state: present

- name: system-setup | user | allow 'wheel' group to run sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'

- name: system-setup | user | create user group '{{ config_username }}'
  group:
    name: "{{ config_username }}"
    state: present

- name: system-setup | user | create user '{{ config_username }}'
  user:
    name: "{{ config_username }}"
    groups: 
      - "{{ config_username }}"
      - wheel
    state: present
    create_home: yes