- name: software | utils | basic system utilities
  package:
    name:
      - git
      - openssh
      - man
      - bottom # system monitor (btm)
      - neovim
      - inetutils # provides commands like "hostname"
      - bind # provides commands like nslookup
      - zip
      - unzip
      - lzip
      - dkms # dynamic kernel modules

- name: software | utils | install git, lsd, openssh, man, neovim, etc
  package:
    name:
      - lsd # 'ls' alternative
      - bat # 'cat' alternative
      - alacritty # terminal
      - dmenu # launcher
      - rofi # launcher
      - ranger # console file manager
      - ueberzug # console image preview
      - light # control screen backlight
      - playerctl # control media playback
      - solaar # logitech device manager

- name: software | utils | install fetch (macchina)
  import_role:
    name: paru
  vars:
    package:
      - macchina

- name: software | utils | check if plugin manager for neovim is already installed
  become: yes
  become_user: "{{ config_username }}"
  stat:
    path: /home/{{ config_username }}/.local/share/nvim/site/autoload/plug.vim
  register: plugin_manager_stat

- name: software | utils | install plugin manager for neovim
  become: yes
  become_user: "{{ config_username }}"
  shell: curl -fLo /home/{{ config_username }}/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  when: not plugin_manager_stat.stat.exists

- name: software | utils | install plugins for neovim (if nvim configs have changed)
  when: userconfig_stat.changed and userconfig_stat.results | selectattr("item.src", "equalto", "nvim") | map(attribute="changed")
  become: yes
  become_user: "{{ config_username }}"
  shell: 'nvim +PlugInstall +qa --headless'
  